---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  this: http://marks.test/this/
  HP: http://purl.obolibrary.org/obo/HP_
sources:
  dhad:
    access: "dhad.csv"
    referenceFormulation: "csv"
    iterator: "$"
mappings:
  person:
    sources:
    - dhad
    s: this:individual_$(pid)#Person
    po:
    - p: sio:SIO_000228
      o:
        value: this:individual_$(pid)#patientRole
        type: iri
  patientRole:
    sources:
    - dhad
    s: this:individual_$(pid)#patientRole
    po:
    - [a, obo:OBI_0000093]
    - p: sio:SIO_000356
      o:
        value: this:individual_$(pid)#processDiag
        type: iri
  processDiag:
    sources:
    - dhad
    s: this:individual_$(pid)#processDiag
    po:
    - [a, sio:SIO_001001]
    - p: sio:SIO_000229
      o: 
        value: this:individual_$(pid)#diagOutcome
        type: iri
  diagOutcome:
    sources:
    - dhad
    s: this:individual_$(pid)#diagOutcome
    po:
    - p: a
      o:
      - sio:SIO_000340
      - sio:SIO_000015
    - p: sio:SIO_000628
      objects:
      - value: this:individual_$(pid)#disease
        type: iri
  disease:
    sources:
    - dhad
    s: this:individual_$(pid)#disease
    po:
    - p: a
      o: $(ordo_uri)
