---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  this: http://marks.test/this/
  HP: http://purl.obolibrary.org/obo/HP_
sources:
  dhad:
    access: "dhad.csv"
    referenceFormulation: "csv"
    iterator: "$"
mappings:
  person:
    sources:
    - dhad
    s: this:individual_$(pid)#Person
    po:
    - p: sio:SIO_000228
      o:
        value: this:individual_$(pid)#patientRole
        type: iri
  patientRole:
    sources:
    - dhad
    s: this:individual_$(pid)#patientRole
    po:
    - [a, obo:OBI_0000093]
    - p: sio:SIO_000356
      o:
        value: this:individual_$(pid)#processDiag
        type: iri
  processDiag:
    sources:
    - dhad
    s: this:individual_$(pid)#processDiag
    po:
    - [a, sio:SIO_001001]
    - p: sio:SIO_000229
      o: 
        value: this:individual_$(pid)#diagOutcome
        type: iri
  diagOutcome:
    sources:
    - dhad
    s: this:individual_$(pid)#diagOutcome
    po:
    - p: a
      o:
      - sio:SIO_000340
      - sio:SIO_000015
    - p: sio:SIO_000628
      objects:
      - value: this:individual_$(pid)#disease1
        type: iri
      - value: this:individual_$(pid)#disease2
        type: iri
      - value: this:individual_$(pid)#disease3
        type: iri
      - value: this:individual_$(pid)#disease4
        type: iri
      - value: this:individual_$(pid)#disease5
        type: iri
      - value: this:individual_$(pid)#disease6
        type: iri
      - value: this:individual_$(pid)#disease7
        type: iri
      - value: this:individual_$(pid)#disease8
        type: iri
      - value: this:individual_$(pid)#disease9
        type: iri
      - value: this:individual_$(pid)#disease10
        type: iri
  disease1:
    sources:
    - dhad
    s: this:individual_$(pid)#disease1
    po:
    - p: a
      o: $(HP1)
    - p: rdfs:label
      o: $(HP1L)
  disease2:
    sources:
    - dhad
    s: this:individual_$(pid)#disease2
    po:
    - p: a
      o: $(HP2)
    - p: rdfs:label
      o: $(HP2L)
  disease3:
    sources:
    - dhad
    s: this:individual_$(pid)#disease3
    po:
    - p: a
      o: $(HP3)
    - p: rdfs:label
      o: $(HP3L)
  disease4:
    sources:
    - dhad
    s: this:individual_$(pid)#disease4
    po:
    - p: a
      o: $(HP4)
    - p: rdfs:label
      o: $(HP4L)
  disease5:
    sources:
    - dhad
    s: this:individual_$(pid)#disease5
    po:
    - p: a
      o: $(HP5)
    - p: rdfs:label
      o: $(HP5L)
  disease6:
    sources:
    - dhad
    s: this:individual_$(pid)#disease6
    po:
    - p: a
      o: $(HP6)
    - p: rdfs:label
      o: $(HP6L)
  disease7:
    sources:
    - dhad
    s: this:individual_$(pid)#disease7
    po:
    - p: a
      o: $(HP7)
    - p: rdfs:label
      o: $(HP7L)
  disease8:
    sources:
    - dhad
    s: this:individual_$(pid)#disease8
    po:
    - p: a
      o: $(HP8)
    - p: rdfs:label
      o: $(HP8L)
  disease9:
    sources:
    - dhad
    s: this:individual_$(pid)#disease9
    po:
    - p: a
      o: $(HP9)
    - p: rdfs:label
      o: $(HP9L)
  disease10:
    sources:
    - dhad
    s: this:individual_$(pid)#disease10
    po:
    - p: a
      o: $(HP10)
    - p: rdfs:label
      o: $(HP10L)
