---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  this: http://marks.test/this/
sources:
  cde_personal_information-source:
#    access: "|||DATA|||"
#    referenceFormulation: "|||FORMULATION|||"
    access: "personal.csv"
    referenceFormulation: "csv"
    iterator: "$"
mappings:
  identifier_has_value_for_patientRole_age:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_age:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_age
        type: iri
  person_has_role_patientRole_age:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_age
        type: iri
  patientRole_age_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_age
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Patient for age assessment
        datatype: xsd:string
  identifier_has_value_for_patientRole_sex:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_sex:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_sex
        type: iri
  person_has_role_patientRole_sex:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#patientRole_sex
        type: iri
  patientRole_sex_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_sex
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: Patient For Gender Assessment
        datatype: xsd:string
  patientRole_age_realized_age_measuring_procedure:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_age
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#age_measuring_procedure
        type: iri
  age_measuring_procedure_process_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)_process#age_measuring_procedure
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdfs:label
      objects:
        value: age measuring process
        datatype: xsd:string
  patientRole_sex_realized_sex_measuring_procedure:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_sex
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#sex_measuring_procedure
        type: iri
  sex_measuring_procedure_process_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)_process#sex_measuring_procedure
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdfs:label
      objects:
        value: sex measuring process
        datatype: xsd:string
  age_measuring_procedure_process_has_output:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)_process#age_measuring_procedure
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
        type: iri
  age_measuring_procedure_Output_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  age_measuring_procedure_Output_type_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/realizable-entity
        type: iri
  age_measuring_procedure_Output_type_label_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
    po:
    - predicates: rdfs:label
      objects:
        value: Birth Date
        datatype: xsd:string
  age_measuring_procedure_Output_value_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(birthdate)"
        datatype: xsd:dateTime
  sex_measuring_procedure_process_has_output:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)_process#sex_measuring_procedure
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
        type: iri
  sex_measuring_procedure_Output_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  sex_measuring_procedure_Output_type_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/realizable-entity
        type: iri
  sex_measuring_procedure_Output_type_label_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
    po:
    - predicates: rdfs:label
      objects:
        value: Sex
        datatype: xsd:string
  sex_measuring_procedure_Output_value_annotation:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(genderLabel)"
        datatype: xsd:string
  inout_from_age_measuring_procedure_refers_to_concepts:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#age_measuring_procedure_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#birthdateQualityURI_TypedAttributeNode
        type: iri
  inout_from_age_measuring_procedure_refers_to_concept_birthdateQualityURI_type:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#birthdateQualityURI_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: "$(birthdateQualityURI)"
        type: iri
  inout_from_sex_measuring_procedure_refers_to_concepts:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#sex_measuring_procedure_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_$(pid)_$(uniqid)#genderURI_TypedAttributeNode
        type: iri
  inout_from_sex_measuring_procedure_refers_to_concept_genderURI_type:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)_$(uniqid)#genderURI_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: "$(genderURI)"
        type: iri
  person_has_attribute_from_age_measuring_procedure:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/SIO_000008
      objects:
        value: this:individual_$(pid)_$(uniqid)#birthdateQualityURI_TypedAttributeNode
        type: iri
  person_has_attribute_from_sex_measuring_procedure:
    sources:
    - cde_personal_information-source
    s: this:individual_$(pid)#Person
    po:
    - predicates: http://semanticscience.org/resource/SIO_000008
      objects:
        value: this:individual_$(pid)_$(uniqid)#genderURI_TypedAttributeNode
        type: iri
