version: "3"
services:

  cde-box-daemon: 
    image: markw/cde-box-daemon:latest
    container_name: cde-box-daemon
    depends_on:
      - yarrrml_transform
      - rdfizer
    ports:
      - 4567:4567
    volumes:
        - ./data:/data
        - ./config:/config
    networks:
      - default
      - bootstrap_graphdb_net          
        
  yarrrml_transform: 
    image: markw/yarrrml-parser-ejp:0.0.3
    container_name: yarrrml_transform
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    networks:
      - default
      - bootstrap_graphdb_net  
  
  rdfizer: 
    image: markw/sdmrdfizer_ejp:0.1.0
    container_name: rdfizer
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
      - ./config:/config
    networks:
      - default
      - bootstrap_graphdb_net
      
  triple_loader: 
    build: ./triple-loader
    volumes:
        - ./data:/data
    environment:
      - "GRAPH_DB_URL=http://graphdb:7200"
      - "REPO_ID=cde"
      - "FILE_PATH=/data/triples/concatenated.nt"
      - "CONTENT_TYPE=application/n-triples"
    networks:
      - default
      - bootstrap_graphdb_net 
        
# Define networks here
networks:
  bootstrap_graphdb_net:
    external: true
